image: ubuntu:xenial

stages:
    - test
    - pages
    - release

before_script:
    - apt-get update
    - apt-get install -y software-properties-common
    - apt-add-repository universe
    - apt-get update
    - apt-get install -y python3 python3-pip make python3-numpy python3-matplotlib hmmer 
    - alias python=python3; pip install --upgrade pip
    - alias python=python3; pip install sphinx sphinx-argparse sphinx_rtd_theme pytest pandas
    - hash -r pip
    - alias python=python3; pip install -e ./

  
do_testing:
  stage: test
  script:
    - alias python=python3; make test
  except:
    - tags
    
