image: ubuntu:xenial

stages:
    - test
    - pages
    - release

before_script:
    - apt-get update
    - apt-get remove python
    - apt-get install -y python3 python3-pip make python3-numpy python3-matplotlib hmmer 
    - update-alternatives --install /usr/bin/python python /usr/bin/python3 10
    - alias python=python3; pip3 install --upgrade pip
    - hash -r pip3
    - alias python=python3; pip3 install sphinx sphinx-argparse sphinx_rtd_theme pytest pandas
    - alias python=python3; pip3 install -e ./

  
do_testing:
  stage: test
  script:
    - alias python=python3; make test
  except:
    - tags
    
